storage:
  path: /Users/kuba/Downloads/blob_storage
  directory-prefix-length: 2

hash:
  algorithm: SHA-256

regex:
    sort: ([a-zA-Z]+):(asc|desc)(?:,|$)
    sort-pattern: (([a-zA-Z]+):(asc|desc)(?:,|$))+
    filter: ([a-zA-Z]+):([^,]+)(?:,|$)
    filter-pattern: (([a-zA-Z]+):([^,]+)(?:,|$))+

spring:
  profiles:
    active: postgresql # set db that you want to use - postgresql / oracle / mssql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  jpa:
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.yaml

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml

---

# PostgreSQL config

spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5433/dms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create-drop

---

# Oracle config

spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    driver-class-name: oracle.jdbc.OracleDriver
    username: SYSTEM
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update

---

# MS SQL config

spring:
  config:
    activate:
      on-profile: mssql
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=dms;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
