#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/dms
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 200MB
#      max-request-size: 200MB
#
#---

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    driver-class-name: oracle.jdbc.OracleDriver
    username: SYSTEM
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB