spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            revision_field_name: revision_id
            revision_type_field_name: revision_type
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

#---
#
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
#    driver-class-name: oracle.jdbc.OracleDriver
#    username: SYSTEM
#    password: admin123
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect
#      org:
#        hibernate:
#          envers:
#            audit_table_suffix: _history
#            revision_field_name: revision_id
#            revision_type_field_name: revision_type
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 200MB
#      max-request-size: 200MB

#---
#
#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=dms;encrypt=true;trustServerCertificate=true;
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: sa
#    password: Admin123
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
#      org:
#        hibernate:
#          envers:
#            audit_table_suffix: _history
#            revision_field_name: revision_id
#            revision_type_field_name: revision_type
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 200MB
#      max-request-size: 200MB