# local directory path for blob storage and length for the name of each subdirectory within the blob storage
storage:
  path: /Users/kuba/Downloads/blob_storage
  directory-prefix-length: 2

# hash algorithm used in blob storage
hash:
  algorithm: SHA-256

archive:
  retention-period-days: 60 # define for how many days the document will be retained in the archive

# time till the JWT token expires
token:
  expiration:
    time: 1 # in hours

# paths to keys
rsa:
  private-key: src/main/resources/certs/private.pem
  public-key: src/main/resources/certs/public.pem

server:
  error:
    path: errors # suffix in URL for errors which occur during requests

jasypt:
  encryptor:
    password: secret # define a secret for hashing configuration passwords
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

admin:
  name: admin # set name for the admin
  email: admin@mail.com # set email for the admin
  password: ENC(ZtnVeP1A4OGV0/2F2OdL8fl+K0xMCDSj) # set password for the admin (must match specified password regex from static/schema/User.yaml) - encrypted using jasypt

spring:
  profiles:
    active: h2 # set database that you want to use
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  jpa:
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  main:
    log-startup-info: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

# H2 config

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:dms:DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa # set username
    password: ENC(A4vM9z16ydTrAzRcK5wFHA==) # set password - encrypted using jasypt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---

# PostgreSQL config

spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/dms
    driver-class-name: org.postgresql.Driver
    username: postgres # set username
    password: ENC(No2GtUHq7YYu6RsZHN0Dzprk681eaCEi) # set password - encrypted using jasypt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---

# Oracle config

spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    driver-class-name: oracle.jdbc.OracleDriver
    username: SYSTEM # set username
    password: ENC(D4yla+9MIpCZradWP43RFb9jRTDp4Mlw) # set password - encrypted using jasypt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

---

# MS SQL config

spring:
  config:
    activate:
      on-profile: mssql
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=dms;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa # set username
    password: ENC(cvRJOx80N7kzIs/X17PafTs1HMobcE04) # set password - encrypted using jasypt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
