storage:
  path: /Users/kuba/Downloads/blob_storage
  directory-prefix-length: 2

hash:
  algorithm: SHA-256

rsa:
  private-key: src/main/resources/certs/private.pem
  public-key: src/main/resources/certs/public.pem

server:
  error:
    path: /errors

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: postgresql # set db that you want to use
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  jpa:
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  main:
    log-startup-info: false
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml

---

# H2 config

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:dms:DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---

# PostgreSQL config

spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/dms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---

# Oracle config

spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    driver-class-name: oracle.jdbc.OracleDriver
    username: SYSTEM
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

---

# MS SQL config

spring:
  config:
    activate:
      on-profile: mssql
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=dms;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
