openapi: 3.1.0

info:
  title: DMS
  summary: Document Management System for Software Documentation
  version: "1.0"

servers:
  - url: http://localhost:8080
    description: Local server

components:
  schemas:
    User:
      type: object
      properties:
        firstname:
          type: string
        email:
          type: string

paths:
  /documents:
    get:
      description: Returns a list of documents.
      tags:
        - documents
      responses:
        200:
          description: A list of Users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        400:
          description: A JSON array of user names
          content:
            text/json:
              schema:
                type: string

  /documents/{id}:
    get:
      description: Get document with id.
      tags:
        - documents
    put:
      description: Update document with id.
      tags:
        - documents
    delete:
      description: Delete document with id.
      tags:
        - documents

  /documents/upload:
    post:
      description: Upload a document.
      tags:
        - documents

  /documents/{id}/download:
    get:
      description: Download a document.
      tags:
        - documents

  /documents/{id}/revisions:
    get:
      description: List document revisions.
      tags:
        - documents
    post:
      description: Upload document revision.
      tags:
        - documents

  /documents/{id}/revisions/{revision}:
    put:
      description: Switch document to a specific revision.
      tags:
        - documents

  /documents/{id}/versions:
    get:
      description: List document versions.
      tags:
        - documents

  /documents/{id}/versions/{version}:
    get:
      description: Get document version.
      tags:
        - documents
    put:
      description: Switch document to a specific version.
      tags:
        - documents

  /revisions:
    get:
      description: List all revisions.
      tags:
        - revisions

  /revisions/{id}:
    get:
      description: Get a revision.
      tags:
        - revisions
    delete:
      description: Delete revision.
      tags:
        - revisions

  /revisions/{id}/download:
    get:
      description: Download a revision.
      tags:
        - revisions

  /users/{id}:
    get:
      description: Returns a User by ID.
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          description: User ID.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                type: object
                $ref: '#/components/schemas/User'
  /files:
    post:
      description: List all files
      tags:
        - files
      responses:
        200:
          description: JSON array of files
          content:
            application/json:
              schema:
                type: array
                items:
                  type: int