openapi: 3.0.3

info:
  title: DMS
  description: Document Management System for Software Documentation
  version: "1.0"

servers:
  - url: http://localhost:8080
    description: Local server

components:

  schemas:

    User:
      $ref: './schema/User.yaml'
    Document:
      $ref: './schema/Document.yaml'
    DocumentWithVersion:
      $ref: './schema/DocumentWithVersion.yaml'
    DocumentRevision:
      $ref: './schema/DocumentRevision.yaml'
    PageWithDocuments:
      $ref: './schema/PageWithDocuments.yaml'
    PageWithRevisions:
      $ref: './schema/PageWithRevisions.yaml'
    PageWithVersions:
      $ref: './schema/PageWithVersions.yaml'
    ClientError:
      $ref: './schema/ClientError.yaml'

  examples:

    PageableWithDocuments:
      $ref: './example/PageableWithDocuments.yaml'
    PageableWithRevisions:
      $ref: './example/PageableWithRevisions.yaml'
    PageableWithVersions:
      $ref: './example/PageableWithVersions.yaml'

  parameters:

    DocumentId:
      $ref: './parameter/DocumentId.yaml'
    RevisionId:
      $ref: './parameter/RevisionId.yaml'
    DocumentVersion:
      $ref: './parameter/DocumentVersion.yaml'
    Page:
      $ref: './parameter/Page.yaml'
    Limit:
      $ref: './parameter/Limit.yaml'
    DocumentSort:
      $ref: './parameter/DocumentSort.yaml'
    RevisionSort:
      $ref: './parameter/RevisionSort.yaml'
    Filter:
      $ref: './parameter/Filter.yaml'

paths:

  /documents:
    $ref: './path/documents/documents.yaml'

  /documents/upload:
    $ref: './path/documents/documents@upload.yaml'

  /documents/{documentId}:
    $ref: './path/documents/documents@:documentId.yaml'

  /documents/{documentId}/download:
    $ref: './path/documents/documents@:documentId@download.yaml'

  /documents/{documentId}/move:
    $ref: './path/documents/documents@:documentId@move.yaml'

  /documents/{documentId}/revisions:
    $ref: './path/documents/documents@:documentId@revisions.yaml'

  /documents/{documentId}/revisions/{revisionId}:
    $ref: './path/documents/documents@:documentId@revisions@:revisionId.yaml'

  /documents/{documentId}/versions:
    $ref: './path/documents/documents@:documentId@versions.yaml'

  /documents/{documentId}/versions/{version}:
    $ref: './path/documents/documents@:documentId@versions@:version.yaml'

  /revisions:
    $ref: './path/revisions/revisions.yaml'

  /revisions/{revisionId}:
    $ref: './path/revisions/revisions@:revisionId.yaml'

  /revisions/{revisionId}/download:
    $ref: './path/revisions/revisions@:revisionId@download.yaml'
