openapi: 3.0.3

info:
  title: DMS
  description: Document Management System for Software Documentation
  version: "1.0"

servers:
  - url: http://localhost:8080
    description: Local server

components:

  schemas:

    User:
      $ref: './schema/User.yaml'
    Destination:
      $ref: './schema/Destination.yaml'
    Document:
      $ref: './schema/Document.yaml'
    DocumentRevision:
      $ref: './schema/DocumentRevision.yaml'
    PageWithDocuments:
      $ref: './schema/PageWithDocuments.yaml'
    PageWithRevisions:
      $ref: './schema/PageWithRevisions.yaml'
    Pageable:
      $ref: './schema/Pageable.yaml'
    Sort:
      $ref: './schema/Sort.yaml'
    ClientError:
      $ref: './schema/ClientError.yaml'

paths:

  /oauth2/authorize:
    $ref: './path/oauth2/oauth2_authorize.yaml'

  /oauth2/revoke:
    $ref: './path/oauth2/oauth2_revoke.yaml'

  /oauth2/token:
    $ref: './path/oauth2/oauth2_token.yaml'

  /documents:
    $ref: './path/documents/documents.yaml'

  /documents/upload:
    $ref: './path/documents/documents_upload.yaml'

  /documents/{documentId}:
    $ref: './path/documents/documents_documentId.yaml'

  /documents/{documentId}/download:
    $ref: './path/documents/documents_documentId_download.yaml'

  /documents/{documentId}/move:
    $ref: './path/documents/documents_documentId_move.yaml'

  /documents/{documentId}/revisions:
    $ref: './path/documents/documents_documentId_revisions.yaml'

  /documents/{documentId}/revisions/{revisionId}:
    $ref: './path/documents/documents_documentId_revisions_revisionId.yaml'

  /revisions:
    $ref: './path/revisions/revisions.yaml'

  /revisions/{revisionId}:
    $ref: './path/revisions/revisions_revisionId.yaml'

  /revisions/{revisionId}/download:
    $ref: './path/revisions/revisions_revisionId_download.yaml'

  /users:
    $ref: './path/users/users.yaml'

  /users/me:
    $ref: './path/users/users_me.yaml'

  /users/{userId}:
    $ref: './path/users/users_userId.yaml'
